/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resources;

import static java.time.Clock.system;
import static java.time.InstantSource.system;
import javax.swing.JOptionPane;
import model.Apartment;
import model.ApartmentDirectory;
import model.Person;

/**
 *
 * @author renuka
 */
public class listApartJpanel extends javax.swing.JPanel {
    /**
    private static void showMessageDialog(listApartJpanel This, String listApartment_Successfull) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }   */

    /**
     * Creates new form listApartJpanel
     */
    ApartmentDirectory apartmentDirectory = new ApartmentDirectory();
    Person person;
    public listApartJpanel(Person person) {
        initComponents();
        this.person = person;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addApartJlable = new javax.swing.JLabel();
        propertyTypeJlable = new javax.swing.JLabel();
        addApartJtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BedsJComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BathsComboBox = new javax.swing.JComboBox<>();
        addjbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        streetNameJtext = new javax.swing.JTextField();
        propertyTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cityJtext = new javax.swing.JTextField();
        unitNoJlabel = new javax.swing.JLabel();
        unitNoJtext = new javax.swing.JTextField();
        SharedRentJcheckbox = new java.awt.Checkbox();
        jLabel5 = new javax.swing.JLabel();
        ownerIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addjbutton1 = new javax.swing.JButton();
        rent = new javax.swing.JLabel();
        rentjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addApartJlable.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        addApartJlable.setText("Apartment Number :");
        add(addApartJlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        propertyTypeJlable.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        propertyTypeJlable.setText("Property Type   :");
        add(propertyTypeJlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 165, -1));

        addApartJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApartJtextActionPerformed(evt);
            }
        });
        add(addApartJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 131, -1));

        jLabel1.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beds  : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 165, -1));

        BedsJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Studio", "1", "2", "3", "4+" }));
        BedsJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedsJComboBoxActionPerformed(evt);
            }
        });
        add(BedsJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 131, -1));

        jLabel2.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Baths  :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 165, -1));

        BathsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "1", "1.5", "2", "2.5", "3+" }));
        add(BathsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 131, -1));

        addjbutton.setText("Add");
        addjbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        addjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbuttonActionPerformed(evt);
            }
        });
        add(addjbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 511, 90, 30));

        jLabel3.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel3.setText("Street Address  : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 165, -1));

        streetNameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameJtextActionPerformed(evt);
            }
        });
        add(streetNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 320, 139, -1));

        propertyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Condo", "House", "Apartment Unit", "Townhouse" }));
        propertyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyTypeComboBoxActionPerformed(evt);
            }
        });
        add(propertyTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 131, -1));

        jLabel4.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("City  :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 165, -1));

        cityJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJtextActionPerformed(evt);
            }
        });
        add(cityJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 139, -1));

        unitNoJlabel.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        unitNoJlabel.setText("Unit Number  :");
        add(unitNoJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 165, -1));

        unitNoJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitNoJtextActionPerformed(evt);
            }
        });
        add(unitNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 139, -1));

        SharedRentJcheckbox.setBackground(new java.awt.Color(255, 255, 255));
        SharedRentJcheckbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SharedRentJcheckbox.setFont(new java.awt.Font("Klee", 1, 16)); // NOI18N
        SharedRentJcheckbox.setLabel("This is a room for rent with a shared living space");
        add(SharedRentJcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel5.setText("Owner ID :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));
        add(ownerIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 131, -1));

        jLabel6.setFont(new java.awt.Font("Hoefler Text", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("List Apartment");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 263, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/apartments (3).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        addjbutton1.setText("Sign Out");
        addjbutton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        addjbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbutton1ActionPerformed(evt);
            }
        });
        add(addjbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 511, 80, 30));

        rent.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        rent.setText("Rent Per Month  :");
        add(rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 165, -1));

        rentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentjTextFieldActionPerformed(evt);
            }
        });
        add(rentjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 139, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/listapt.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1810, 1070));
    }// </editor-fold>//GEN-END:initComponents

    private void addApartJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApartJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addApartJtextActionPerformed

    private void BedsJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedsJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedsJComboBoxActionPerformed

    private void streetNameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameJtextActionPerformed
        // TODO add your handling code here:
        //TODO:Use google maps API to fetch location

    }//GEN-LAST:event_streetNameJtextActionPerformed

    private void addjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbuttonActionPerformed
        // TODO add your handling code here:
        String apartmentNumber = addApartJtext.getText();
        String propertyType = (String) propertyTypeComboBox.getSelectedItem();
        String beds = (String) BedsJComboBox.getSelectedItem();
        String bath = (String) BathsComboBox.getSelectedItem();
        String unitNumber = unitNoJtext.getText();
        String streetAddress = streetNameJtext.getText();
        String city = cityJtext.getText();
        String rent = rentjTextField.getText();


            JOptionPane.showMessageDialog(this,"Apartment Added Succesfully!!");


        
    }//GEN-LAST:event_addjbuttonActionPerformed

    private void propertyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyTypeComboBoxActionPerformed

    private void unitNoJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitNoJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitNoJtextActionPerformed

    private void cityJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJtextActionPerformed

    private void addjbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addjbutton1ActionPerformed

    private void rentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BathsComboBox;
    private javax.swing.JComboBox<String> BedsJComboBox;
    public static transient volatile java.awt.Checkbox SharedRentJcheckbox;
    private javax.swing.JLabel addApartJlable;
    private javax.swing.JTextField addApartJtext;
    private javax.swing.JButton addjbutton;
    private javax.swing.JButton addjbutton1;
    private javax.swing.JTextField cityJtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ownerIDTextField;
    private javax.swing.JComboBox<String> propertyTypeComboBox;
    private javax.swing.JLabel propertyTypeJlable;
    private javax.swing.JLabel rent;
    private javax.swing.JTextField rentjTextField;
    private javax.swing.JTextField streetNameJtext;
    private javax.swing.JLabel unitNoJlabel;
    private javax.swing.JTextField unitNoJtext;
    // End of variables declaration//GEN-END:variables


}
