/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import javax.swing.JOptionPane;

/**
 *
 * @author renuka
 */
public class addDriverJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addDriverJPanel
     */
    public addDriverJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        emailjText = new javax.swing.JTextField();
        AddressjTextField = new javax.swing.JTextField();
        addDriverJbutton = new javax.swing.JButton();
        NameJlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ContactJlabel = new javax.swing.JLabel();
        LnamejTextField = new javax.swing.JTextField();
        AgejTextField = new javax.swing.JTextField();
        emailJlabel = new javax.swing.JLabel();
        addressJlabel = new javax.swing.JLabel();
        agejLabel = new javax.swing.JLabel();
        FnamejText = new javax.swing.JTextField();
        driverIDJlable = new javax.swing.JLabel();
        contactjText = new javax.swing.JTextField();
        driverIDjText = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        LnojTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tripsjText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        shiftjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        availabilityjDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.hoverBorderColor"));

        emailjText.setForeground(new java.awt.Color(1, 1, 1));

        AddressjTextField.setForeground(new java.awt.Color(1, 1, 1));
        AddressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextFieldActionPerformed(evt);
            }
        });

        addDriverJbutton.setText("Add");
        addDriverJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverJbuttonActionPerformed(evt);
            }
        });

        NameJlabel.setForeground(new java.awt.Color(1, 1, 1));
        NameJlabel.setText("First Name     :");

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Last Name  : ");

        ContactJlabel.setForeground(new java.awt.Color(1, 1, 1));
        ContactJlabel.setText("Contact   :");

        LnamejTextField.setForeground(new java.awt.Color(1, 1, 1));

        AgejTextField.setForeground(new java.awt.Color(1, 1, 1));

        emailJlabel.setForeground(new java.awt.Color(1, 1, 1));
        emailJlabel.setText("Email      :");

        addressJlabel.setForeground(new java.awt.Color(1, 1, 1));
        addressJlabel.setText("Address   :  ");

        agejLabel.setForeground(new java.awt.Color(1, 1, 1));
        agejLabel.setText("Age   :   ");

        FnamejText.setForeground(new java.awt.Color(1, 1, 1));

        driverIDJlable.setForeground(new java.awt.Color(1, 1, 1));
        driverIDJlable.setText("Driver ID  : ");

        contactjText.setForeground(new java.awt.Color(1, 1, 1));

        driverIDjText.setForeground(new java.awt.Color(1, 1, 1));

        jLabel.setForeground(new java.awt.Color(1, 1, 1));
        jLabel.setText("Liscence Number   : ");

        LnojTextField.setForeground(new java.awt.Color(1, 1, 1));

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Total No. of trips compelted   :");

        tripsjText.setForeground(new java.awt.Color(1, 1, 1));

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Shift   : ");

        shiftjTextField.setForeground(new java.awt.Color(1, 1, 1));
        shiftjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftjTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Availability   :");

        availabilityjDateChooser.setForeground(new java.awt.Color(1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Hoefler Text", 1, 36)); // NOI18N
        jLabel5.setText("Add Driver Details");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/license (1) (1).png"))); // NOI18N

        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 204, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Kavivanar", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Best Driver Checklist\n✓Punctual\n✓Reliable\n✓Honest ");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/he.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(driverIDJlable, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addDriverJbutton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availabilityjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FnamejText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(contactjText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(71, 71, 71)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(addressJlabel)
                                                    .addComponent(agejLabel))))
                                        .addComponent(emailjText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(driverIDjText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tripsjText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LnojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shiftjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(667, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)))
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(368, 368, 368))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverIDJlable)
                            .addComponent(driverIDjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel)
                            .addComponent(LnojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameJlabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FnamejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(LnamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContactJlabel)
                            .addComponent(contactjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agejLabel)
                            .addComponent(AgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailJlabel)
                                    .addComponent(emailjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressJlabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(AddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tripsjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(shiftjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(availabilityjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(addDriverJbutton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

    }// </editor-fold>//GEN-END:initComponents

    private void AddressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextFieldActionPerformed

    private void shiftjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftjTextFieldActionPerformed

    private void addDriverJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverJbuttonActionPerformed
        // TODO add your handling code here:
         String driverIDJlable = driverIDjText.getText();
        String NameJlabel = (String) FnamejText.getText();
        String ContactJlabel = (String) contactjText.getText();
        String emailJlabel = (String) emailjText.getText();
        String jLable1 = tripsjText.getText();
        String City = LnojTextField.getText();
        String jLabel = LnamejTextField.getText();
        String agejLabel = AgejTextField.getText();
        String addressJlabel = AddressjTextField.getText();
        String jlabel2 = LnamejTextField.getText();
        String jlabel3 = shiftjTextField.getText();

            JOptionPane.showMessageDialog(this,"Driver Added Succesfully!!");
            
            driverIDjText.setText("");
            FnamejText.setText("");
            contactjText.setText("");
            emailjText.setText("");
            tripsjText.setText("");
            LnojTextField.setText("");
            LnamejTextField.setText("");
            AgejTextField.setText("");
            AddressjTextField.setText("");
            LnamejTextField.setText("");
            shiftjTextField.setText("");

    }//GEN-LAST:event_addDriverJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressjTextField;
    private javax.swing.JTextField AgejTextField;
    private javax.swing.JLabel ContactJlabel;
    private javax.swing.JTextField FnamejText;
    private javax.swing.JTextField LnamejTextField;
    private javax.swing.JTextField LnojTextField;
    private javax.swing.JLabel NameJlabel;
    private javax.swing.JButton addDriverJbutton;
    private javax.swing.JLabel addressJlabel;
    private javax.swing.JLabel agejLabel;
    private com.toedter.calendar.JDateChooser availabilityjDateChooser;
    private javax.swing.JTextField contactjText;
    private javax.swing.JLabel driverIDJlable;
    private javax.swing.JTextField driverIDjText;
    private javax.swing.JLabel emailJlabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField shiftjTextField;
    private javax.swing.JTextField tripsjText;
    // End of variables declaration//GEN-END:variables
}
