/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design;



/**
 *
 * @author renuka
 */
public class AdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        createBrokerJbutton = new javax.swing.JButton();
        viewBrokerJbutton = new javax.swing.JButton();
        updateBrokerJbutton = new javax.swing.JButton();
        viewListingJbutton = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createBrokerJbutton.setText("Create Broker");
        createBrokerJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBrokerJbuttonActionPerformed(evt);
            }
        });

        viewBrokerJbutton.setText("View Broker");
        viewBrokerJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBrokerJbuttonActionPerformed(evt);
            }
        });

        updateBrokerJbutton.setText("Update Broker");
        updateBrokerJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBrokerJbuttonActionPerformed(evt);
            }
        });

        viewListingJbutton.setText("View Listings");
        viewListingJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListingJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createBrokerJbutton)
                    .addComponent(viewBrokerJbutton)
                    .addComponent(updateBrokerJbutton)
                    .addComponent(viewListingJbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createBrokerJbutton, updateBrokerJbutton, viewBrokerJbutton, viewListingJbutton});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(createBrokerJbutton)
                .addGap(18, 18, 18)
                .addComponent(viewBrokerJbutton)
                .addGap(18, 18, 18)
                .addComponent(updateBrokerJbutton)
                .addGap(18, 18, 18)
                .addComponent(viewListingJbutton)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createBrokerJbutton, updateBrokerJbutton, viewBrokerJbutton, viewListingJbutton});

        SplitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBrokerJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBrokerJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBrokerJbuttonActionPerformed

    private void viewListingJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListingJbuttonActionPerformed
        // TODO add your handling code here:
        listingsJPanel jp = new listingsJPanel();
        SplitPane.setRightComponent(jp);
    }//GEN-LAST:event_viewListingJbuttonActionPerformed

    private void createBrokerJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBrokerJbuttonActionPerformed
        // TODO add your handling code here:
        createBrokerJPanel cb = new createBrokerJPanel();
        SplitPane.setRightComponent(cb);
                

    }//GEN-LAST:event_createBrokerJbuttonActionPerformed

    private void viewBrokerJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBrokerJbuttonActionPerformed
        // TODO add your handling code here:
        viewBrokerJPanel vb = new viewBrokerJPanel();
        SplitPane.setRightComponent(vb);
        
    }//GEN-LAST:event_viewBrokerJbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton createBrokerJbutton;
    private javax.swing.JButton updateBrokerJbutton;
    private javax.swing.JButton viewBrokerJbutton;
    private javax.swing.JButton viewListingJbutton;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
