/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import static java.time.Clock.system;
import static java.time.InstantSource.system;
import javax.swing.JOptionPane;
import model.Apartment;
import model.ApartmentDirectory;
import model.Person;

/**
 *
 * @author renuka
 */
public class listApartJpanel extends javax.swing.JPanel {
    /** 
    private static void showMessageDialog(listApartJpanel This, String listApartment_Successfull) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }   */

    /**
     * Creates new form listApartJpanel
     */
    ApartmentDirectory apartmentDirectory = new ApartmentDirectory();
    Person person;
    public listApartJpanel(Person person) {
        initComponents();
        this.person = person;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addApartJlable = new javax.swing.JLabel();
        propertyTypeJlable = new javax.swing.JLabel();
        addApartJtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BedsJComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BathsComboBox = new javax.swing.JComboBox<>();
        addjbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        streetNameJtext = new javax.swing.JTextField();
        propertyTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cityJtext = new javax.swing.JTextField();
        unitNoJlabel = new javax.swing.JLabel();
        unitNoJtext = new javax.swing.JTextField();
        SharedRentJcheckbox = new java.awt.Checkbox();
        jLabel5 = new javax.swing.JLabel();
        ownerIDTextField = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        addApartJlable.setText("Apartment Number :");

        propertyTypeJlable.setText("Property Type   :");

        addApartJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApartJtextActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beds  : ");

        BedsJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Studio", "1", "2", "3", "4+" }));
        BedsJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedsJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Baths  :");

        BathsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "1", "1.5", "2", "2.5", "3+" }));

        addjbutton.setText("Add");
        addjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbuttonActionPerformed(evt);
            }
        });

        jLabel3.setText("Street Address  : ");

        streetNameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameJtextActionPerformed(evt);
            }
        });

        propertyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Condo", "House", "Apartment Unit", "Townhouse" }));
        propertyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("City  :");

        cityJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJtextActionPerformed(evt);
            }
        });

        unitNoJlabel.setText("Unit Number  :");

        unitNoJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitNoJtextActionPerformed(evt);
            }
        });

        SharedRentJcheckbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SharedRentJcheckbox.setLabel("This is a room for rent with a shared living space");

        jLabel5.setText("Owner ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SharedRentJcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addApartJlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(propertyTypeJlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BedsJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(propertyTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BathsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addApartJtext, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(ownerIDTextField))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(addjbutton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unitNoJlabel)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(unitNoJtext, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(streetNameJtext)))))))
                .addGap(119, 119, 119))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addApartJlable, jLabel1, jLabel2, jLabel4, propertyTypeJlable});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ownerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitNoJlabel)
                    .addComponent(unitNoJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addApartJlable)
                    .addComponent(addApartJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(streetNameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertyTypeJlable)
                                .addComponent(propertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BedsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BathsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(cityJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SharedRentJcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(addjbutton)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addApartJlable, jLabel3, jLabel4});

    }// </editor-fold>//GEN-END:initComponents

    private void addApartJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApartJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addApartJtextActionPerformed

    private void BedsJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedsJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedsJComboBoxActionPerformed

    private void streetNameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameJtextActionPerformed
        // TODO add your handling code here:
        //TODO:Use google maps API to fetch location 
        
    }//GEN-LAST:event_streetNameJtextActionPerformed

    private void addjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbuttonActionPerformed
        // TODO add your handling code here:
        String ApartmentNumber = addApartJtext.getText();
        String PropertyType = (String) propertyTypeComboBox.getSelectedItem();
        int Beds = Integer.parseInt((String) BedsJComboBox.getSelectedItem());
        float Bath = Float.parseFloat((String) BathsComboBox.getSelectedItem());
        String UnitNumber = unitNoJtext.getText();
        String StreetAddress = streetNameJtext.getText();
        String City = cityJtext.getText();
        
        int owner = this.person.getId();
        apartmentDirectory.addApartment(owner, ApartmentNumber, StreetAddress, City, "MA", Beds , Bath, PropertyType);


            JOptionPane.showMessageDialog(this,"Apartment Added Succesfully!!");
            
            
        
    }//GEN-LAST:event_addjbuttonActionPerformed

    private void propertyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyTypeComboBoxActionPerformed

    private void unitNoJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitNoJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitNoJtextActionPerformed

    private void cityJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJtextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BathsComboBox;
    private javax.swing.JComboBox<String> BedsJComboBox;
    public static transient volatile java.awt.Checkbox SharedRentJcheckbox;
    private javax.swing.JLabel addApartJlable;
    private javax.swing.JTextField addApartJtext;
    private javax.swing.JButton addjbutton;
    private javax.swing.JTextField cityJtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ownerIDTextField;
    private javax.swing.JComboBox<String> propertyTypeComboBox;
    private javax.swing.JLabel propertyTypeJlable;
    private javax.swing.JTextField streetNameJtext;
    private javax.swing.JLabel unitNoJlabel;
    private javax.swing.JTextField unitNoJtext;
    // End of variables declaration//GEN-END:variables

    
}
