/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import static java.time.Clock.system;
import static java.time.InstantSource.system;
import javax.swing.JOptionPane;
import model.Apartment;
import model.ApartmentDirectory;
import model.Person;

/**
 *
 * @author renuka
 */
public class listApartJpanel extends javax.swing.JPanel {
    /**
    private static void showMessageDialog(listApartJpanel This, String listApartment_Successfull) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }   */

    /**
     * Creates new form listApartJpanel
     */
    ApartmentDirectory apartmentDirectory = new ApartmentDirectory();
    Person person;
    public listApartJpanel(Person person) {
        initComponents();
        this.person = person;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addApartJlable = new javax.swing.JLabel();
        propertyTypeJlable = new javax.swing.JLabel();
        addApartJtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BedsJComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BathsComboBox = new javax.swing.JComboBox<>();
        addjbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        streetNameJtext = new javax.swing.JTextField();
        propertyTypeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cityJtext = new javax.swing.JTextField();
        unitNoJlabel = new javax.swing.JLabel();
        unitNoJtext = new javax.swing.JTextField();
        SharedRentJcheckbox = new java.awt.Checkbox();
        jLabel5 = new javax.swing.JLabel();
        ownerIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addjbutton1 = new javax.swing.JButton();
        rent = new javax.swing.JLabel();
        rentjTextField = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(255, 153, 153));

        addApartJlable.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        addApartJlable.setText("Apartment Number :");

        propertyTypeJlable.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        propertyTypeJlable.setText("Property Type   :");

        addApartJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApartJtextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beds  : ");

        BedsJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Studio", "1", "2", "3", "4+" }));
        BedsJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedsJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Baths  :");

        BathsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "1", "1.5", "2", "2.5", "3+" }));

        addjbutton.setText("Add");
        addjbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        addjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbuttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel3.setText("Street Address  : ");

        streetNameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameJtextActionPerformed(evt);
            }
        });

        propertyTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Condo", "House", "Apartment Unit", "Townhouse" }));
        propertyTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("City  :");

        cityJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJtextActionPerformed(evt);
            }
        });

        unitNoJlabel.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        unitNoJlabel.setText("Unit Number  :");

        unitNoJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitNoJtextActionPerformed(evt);
            }
        });

        SharedRentJcheckbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SharedRentJcheckbox.setFont(new java.awt.Font("Klee", 1, 16)); // NOI18N
        SharedRentJcheckbox.setLabel("This is a room for rent with a shared living space");

        jLabel5.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        jLabel5.setText("Owner ID :");

        jLabel6.setFont(new java.awt.Font("Hoefler Text", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("List Apartment");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/apartments (3).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Screenshot 2022-12-07 at 6.14.56 PM.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        addjbutton1.setText("Sign Out");
        addjbutton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        addjbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjbutton1ActionPerformed(evt);
            }
        });

        rent.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        rent.setText("Rent Per Month  :");

        rentjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addjbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addjbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(addApartJlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(49, 49, 49))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(47, 47, 47)
                                                    .addComponent(jLabel5))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(45, 45, 45)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(propertyTypeJlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SharedRentJcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BedsJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BathsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addApartJtext)
                                        .addComponent(ownerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(propertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(unitNoJlabel)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rent)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(34, 34, 34))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(streetNameJtext, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unitNoJtext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(cityJtext, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentjTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(435, 435, 435)))
                .addGap(0, 441, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addApartJlable, jLabel1, jLabel2, jLabel3, jLabel4, propertyTypeJlable, rent, unitNoJlabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(ownerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(addApartJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(addApartJlable)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(propertyTypeJlable)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(propertyTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(unitNoJlabel)
                                            .addComponent(unitNoJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(streetNameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BedsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rent)
                                    .addComponent(rentjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BathsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SharedRentJcheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addjbutton)
                            .addComponent(addjbutton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addApartJlable, jLabel3, jLabel4, rent, unitNoJlabel});

    }// </editor-fold>//GEN-END:initComponents

    private void addApartJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApartJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addApartJtextActionPerformed

    private void BedsJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedsJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedsJComboBoxActionPerformed

    private void streetNameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameJtextActionPerformed
        // TODO add your handling code here:
        //TODO:Use google maps API to fetch location

    }//GEN-LAST:event_streetNameJtextActionPerformed

    private void addjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbuttonActionPerformed
        // TODO add your handling code here:
        
        String apartmentNumber = addApartJtext.getText();
        String propertyType = (String) propertyTypeComboBox.getSelectedItem();
        int beds = Integer.parseInt((String) BedsJComboBox.getSelectedItem());
        float bath = Float.parseFloat((String) BathsComboBox.getSelectedItem());
        String unitNumber = unitNoJtext.getText();
        String streetAddress = streetNameJtext.getText();
        String city = cityJtext.getText();
        int rent = Integer.parseInt(rentjTextField.getText());
        
        apartmentDirectory.addApartment(person.getId(), apartmentNumber, unitNumber, city, "MA", beds, bath, propertyType, rent);
        

        
    }//GEN-LAST:event_addjbuttonActionPerformed

    private void propertyTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertyTypeComboBoxActionPerformed

    private void unitNoJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitNoJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitNoJtextActionPerformed

    private void cityJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJtextActionPerformed

    private void addjbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addjbutton1ActionPerformed

    private void rentjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BathsComboBox;
    private javax.swing.JComboBox<String> BedsJComboBox;
    public static transient volatile java.awt.Checkbox SharedRentJcheckbox;
    private javax.swing.JLabel addApartJlable;
    private javax.swing.JTextField addApartJtext;
    private javax.swing.JButton addjbutton;
    private javax.swing.JButton addjbutton1;
    private javax.swing.JTextField cityJtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ownerIDTextField;
    private javax.swing.JComboBox<String> propertyTypeComboBox;
    private javax.swing.JLabel propertyTypeJlable;
    private javax.swing.JLabel rent;
    private javax.swing.JTextField rentjTextField;
    private javax.swing.JTextField streetNameJtext;
    private javax.swing.JLabel unitNoJlabel;
    private javax.swing.JTextField unitNoJtext;
    // End of variables declaration//GEN-END:variables


}
