/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resources;

import design.viewContractsJPanel;
import model.Person;

/**
 *
 * @author renuka
 */
public class ownerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ownerJFrame
     * @param person
     */
    
    static Person person;
    public ownerJFrame(Person person) {
        this.person = person;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        listApartJbutton = new javax.swing.JButton();
        viewContractJbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(153, 153, 153));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listApartJbutton.setText("List Apartment");
        listApartJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listApartJbuttonActionPerformed(evt);
            }
        });
        controlPanel.add(listApartJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 419, 143, -1));

        viewContractJbutton.setText("View Contracts");
        viewContractJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewContractJbuttonActionPerformed(evt);
            }
        });
        controlPanel.add(viewContractJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 504, 143, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1k.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        controlPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -360, 160, 1640));

        SplitPane.setLeftComponent(controlPanel);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/120.png"))); // NOI18N

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 637, Short.MAX_VALUE))
        );

        SplitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listApartJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listApartJbuttonActionPerformed
        // TODO add your handling code here:
        listApartJpanel l = new listApartJpanel(person);
        SplitPane.setRightComponent(l);
    }//GEN-LAST:event_listApartJbuttonActionPerformed

    private void viewContractJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewContractJbuttonActionPerformed
        // TODO add your handling code here:
        viewContractsJPanel j = new viewContractsJPanel();
        SplitPane.setRightComponent(j);
    }//GEN-LAST:event_viewContractJbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerJFrame(person).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton listApartJbutton;
    private javax.swing.JButton viewContractJbutton;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
