/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;
import model.Role;

/**
 *
 * @author renuka
 */
public class viewBrokerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewBrokerJPanel
     */
    public viewBrokerJPanel() {

        initComponents();
        PersonDirectory personDirectory = new PersonDirectory();
        List<Person> brokerList = personDirectory.getPersonListByRole(Role.BROKER);
        populateTable(brokerList);
    }

    private void populateTable(List<Person> brokerList) {
        try {
            DefaultTableModel model = (DefaultTableModel) viewBrokerjTable.getModel();

            model.setRowCount(0);
            for (Person d : brokerList) {
                //            VitalRecord vr = e.getVital();
                Object[] row = new Object[7];

                row[0] = d.getId();
                row[1] = d.getuserName();
                row[2] = d.getEmail();
                row[3] = d.getContact();
                row[4] = d.getAddress();
                row[5] = d.getAge();

                model.addRow(row);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewBrokerjTable = new javax.swing.JTable();
        signOutJbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        viewBrokerjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Broker ID", "Name", "Email", "Contact Number", "Address", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewBrokerjTable);

        signOutJbutton.setText("Sign Out");
        signOutJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutJbuttonActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(63, 63, 63)
                        .addComponent(signOutJbutton)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signOutJbutton)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signOutJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton signOutJbutton;
    private javax.swing.JTable viewBrokerjTable;
    // End of variables declaration//GEN-END:variables
}
