/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

/**
 *
 * @author renuka
 */
public class viewContractsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GenerateContractsJPanel
     */
    public viewContractsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewContractJTable = new javax.swing.JTable();
        acceptJbutton = new javax.swing.JButton();
        rejectJbutton = new javax.swing.JButton();
        RemakJlabel = new javax.swing.JLabel();
        remakjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchjTextField = new javax.swing.JTextField();

        viewContractJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Contract ID", "Name", "Email", "Contact Number", "Current Address", "City", "State", "Zip Code", "Tenure", "Security Deposit", "Application Fee", "Budget/Rent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewContractJTable);

        add(jScrollPane1);

        acceptJbutton.setText("Accept");
        add(acceptJbutton);

        rejectJbutton.setText("Reject");
        rejectJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectJbuttonActionPerformed(evt);
            }
        });
        add(rejectJbutton);

        RemakJlabel.setText("Remark : ");
        add(RemakJlabel);
        add(remakjTextField);

        jLabel1.setText("Search : ");
        add(jLabel1);
        add(searchjTextField);
    }// </editor-fold>//GEN-END:initComponents

    private void rejectJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectJbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejectJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RemakJlabel;
    private javax.swing.JButton acceptJbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectJbutton;
    private javax.swing.JTextField remakjTextField;
    private javax.swing.JTextField searchjTextField;
    private javax.swing.JTable viewContractJTable;
    // End of variables declaration//GEN-END:variables
}
